/**
 * This file was automatically generated by Nexus 0.11.7
 * Do not make changes to this file directly
 */

import { core } from 'nexus';
declare global {
  interface NexusGenCustomDefinitionMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void; // "Date";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {
  SkuEnum: '_120P90' | '_234234' | '_43N23P' | '_A304SD';
}

export interface NexusGenRootTypes {
  Checkout: {
    // root type
    items: NexusGenRootTypes['ScannedItem'][]; // [ScannedItem!]!
    total: number; // Float!
  };
  Mutation: {};
  Query: {};
  ScannedItem: {
    // root type
    name: string; // String!
    quantity: number; // Int!
    sku: NexusGenEnums['SkuEnum']; // SkuEnum!
  };
  UploadSummary: {
    // root type
    filename: string; // String!
  };
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  Date: any;
  Upload: any;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  SkuEnum: NexusGenEnums['SkuEnum'];
}

export interface NexusGenFieldTypes {
  Checkout: {
    // field return type
    items: NexusGenRootTypes['ScannedItem'][]; // [ScannedItem!]!
    total: number; // Float!
  };
  Mutation: {
    // field return type
    checkout: NexusGenRootTypes['Checkout']; // Checkout!
  };
  Query: {
    // field return type
    healtCheck: string; // String!
  };
  ScannedItem: {
    // field return type
    name: string; // String!
    quantity: number; // Int!
    sku: NexusGenEnums['SkuEnum']; // SkuEnum!
  };
  UploadSummary: {
    // field return type
    filename: string; // String!
  };
}

export interface NexusGenArgTypes {
  Mutation: {
    checkout: {
      // args
      quantity: number; // Int!
      sku: NexusGenEnums['SkuEnum']; // SkuEnum!
    };
  };
}

export interface NexusGenAbstractResolveReturnTypes {}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = 'Checkout' | 'Mutation' | 'Query' | 'ScannedItem' | 'UploadSummary';

export type NexusGenInputNames = never;

export type NexusGenEnumNames = 'SkuEnum';

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = 'Boolean' | 'Date' | 'Float' | 'ID' | 'Int' | 'String' | 'Upload';

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes'];
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}
